import type { TaskRow, ITTaskRow, DashboardData } from './types';

export const MOCK_TASKS: TaskRow[] = [
  {
    id: 'DA1', project: 'App/Web AK phase 1.2', task: 'Thay đổi thông tin người nhận hàng',
    owner: 'Đức Anh', status: 'Add Xtask', startDate: '2025-11-14', endDate: '2026-06-15',
    detail: '26/11: Trao đổi nhanh với IT về luồng thay đổi thông tin. Cần update màn hình checkout.',
    link: 'https://figma.com', note: null, role: 'PO', sourceSheet: 'Đức Anh', sourceRow: 2,
    itTaskId: 'TASK2606001', lastModified: '2026-05-18T10:00:00Z',
  },
  {
    id: 'DA2', project: 'App/Web AK phase 1.2', task: 'Cổng thanh toán VNPay',
    owner: 'Đức Anh', status: 'Add Sprint', startDate: '2026-04-01', endDate: '2026-05-18',
    detail: 'Tích hợp VNPay vào luồng thanh toán. Đã hoàn thành test sandbox.',
    link: null, note: 'Cần review lại với team IT', role: 'PO', sourceSheet: 'Đức Anh', sourceRow: 3,
    itTaskId: 'TASK2605001', lastModified: '2026-05-17T09:00:00Z',
  },
  {
    id: 'DA3', project: 'Tổng đơn bán kèm', task: 'Thiết kế luồng bundle sản phẩm',
    owner: 'Đức Anh', status: 'In progress', startDate: '2026-05-01', endDate: '2026-05-30',
    detail: 'Thiết kế luồng cho tính năng bundle sản phẩm kèm theo khi checkout.',
    link: 'https://figma.com', note: null, role: 'PO', sourceSheet: 'Đức Anh', sourceRow: 4,
    itTaskId: null, lastModified: '2026-05-19T08:00:00Z',
  },
  {
    id: 'KH1', project: 'Shop in shop', task: 'Mô tả tính năng shop in shop',
    owner: 'Khánh', status: 'Add Sprint', startDate: '2026-05-10', endDate: '2026-05-31',
    detail: 'Mô tả đầy đủ tính năng shop in shop cho các đối tác thương hiệu lớn.',
    link: null, note: null, role: 'PD', sourceSheet: 'Khánh', sourceRow: 2,
    itTaskId: 'TASK2605002', lastModified: '2026-05-18T14:00:00Z',
  },
  {
    id: 'KH2', project: 'App/Web AK phase 1.2', task: 'Màn hình giỏ hàng mobile',
    owner: 'Khánh', status: 'Nghiệm thu', startDate: '2026-04-15', endDate: '2026-05-20',
    detail: 'Redesign màn hình giỏ hàng cho mobile, cải thiện UX checkout.',
    link: 'https://figma.com', note: null, role: 'PD', sourceSheet: 'Khánh', sourceRow: 3,
    itTaskId: 'TASK2605003', lastModified: '2026-05-19T09:00:00Z',
  },
  {
    id: 'KH3', project: 'Roadmap Q3', task: 'PRD tính năng loyalty points',
    owner: 'Khánh', status: 'Chuẩn bị làm', startDate: null, endDate: '2026-07-01',
    detail: null, link: null, note: null, role: 'PD', sourceSheet: 'Khánh', sourceRow: 4,
    itTaskId: null, lastModified: '2026-05-15T10:00:00Z',
  },
  {
    id: 'TY1', project: 'Tổng đơn bán kèm', task: 'Triển khai chiến dịch cross-sell',
    owner: 'Tuyền', status: 'Add Sprint', startDate: '2026-05-05', endDate: '2026-05-26',
    detail: 'Triển khai chiến dịch bán kèm cho mùa hè 2026.',
    link: null, note: null, role: 'DA', sourceSheet: 'Tuyền', sourceRow: 2,
    itTaskId: 'TASK2605004', lastModified: '2026-05-18T11:00:00Z',
  },
  {
    id: 'TY2', project: 'Tổng đơn bán kèm', task: 'Định hình danh sách sản phẩm kèm',
    owner: 'Tuyền', status: 'Done', startDate: '2026-04-01', endDate: '2026-04-10',
    detail: 'Đã hoàn thành danh sách 50 sản phẩm kèm ưu tiên.',
    link: null, note: null, role: 'DA', sourceSheet: 'Tuyền', sourceRow: 3,
    itTaskId: null, lastModified: '2026-04-10T15:00:00Z',
  },
  {
    id: 'TY3', project: 'Voucher & Khuyến mãi', task: 'Luồng áp dụng voucher',
    owner: 'Tuyền', status: 'In progress', startDate: '2026-05-12', endDate: '2026-06-01',
    detail: 'Mô tả luồng áp dụng voucher khi checkout, bao gồm stack discount.',
    link: 'https://docs.google.com', note: null, role: 'DA', sourceSheet: 'Tuyền', sourceRow: 4,
    itTaskId: null, lastModified: '2026-05-19T07:00:00Z',
  },
  {
    id: 'TR1', project: 'App/Web AK phase 1.2', task: 'Màn hình trang chủ v2',
    owner: 'Trang', status: 'Golive', startDate: '2026-03-01', endDate: '2026-04-30',
    detail: 'Redesign hoàn toàn trang chủ với banner động và section sản phẩm mới.',
    link: 'https://figma.com', note: null, role: 'PMC', sourceSheet: 'Trang', sourceRow: 2,
    itTaskId: 'TASK2604001', lastModified: '2026-04-30T16:00:00Z',
  },
  {
    id: 'TR2', project: 'SEO & Performance', task: 'Tối ưu Core Web Vitals',
    owner: 'Trang', status: 'Add Xtask', startDate: '2026-05-01', endDate: '2026-05-25',
    detail: 'Cải thiện LCP, FID, CLS theo checklist từ team IT.',
    link: null, note: 'Chờ team IT deploy xong phase 1.2', role: 'PMC', sourceSheet: 'Trang', sourceRow: 3,
    itTaskId: null, lastModified: '2026-05-17T12:00:00Z',
  },
  {
    id: 'TI1', project: 'Phân tích dữ liệu', task: 'Dashboard báo cáo tuần',
    owner: 'Trình', status: 'Định kỳ', startDate: '2026-01-01', endDate: null,
    detail: 'Báo cáo số liệu tuần cho BGĐ: doanh thu, đơn hàng, conversion rate.',
    link: 'https://lookerstudio.google.com', note: null, role: null, sourceSheet: 'Trình', sourceRow: 2,
    itTaskId: null, lastModified: '2026-05-18T17:00:00Z',
  },
  {
    id: 'TI2', project: 'App/Web AK phase 1.3', task: 'Nghiên cứu tính năng AR try-on',
    owner: 'Trình', status: 'Chuẩn bị làm', startDate: null, endDate: '2026-08-01',
    detail: null, link: null, note: null, role: null, sourceSheet: 'Trình', sourceRow: 3,
    itTaskId: null, lastModified: '2026-05-10T09:00:00Z',
  },
  {
    id: 'MA1', project: 'Chăm sóc khách hàng', task: 'Luồng ticket support',
    owner: 'Mai', status: 'Add Sprint', startDate: '2026-05-08', endDate: '2026-05-22',
    detail: 'Thiết kế luồng ticket support tích hợp vào app AK.',
    link: 'https://figma.com', note: null, role: null, sourceSheet: 'Mai', sourceRow: 2,
    itTaskId: 'TASK2605005', lastModified: '2026-05-18T10:30:00Z',
  },
  {
    id: 'MA2', project: 'Chăm sóc khách hàng', task: 'FAQ tự động chatbot',
    owner: 'Mai', status: 'In progress', startDate: '2026-05-15', endDate: '2026-06-10',
    detail: 'Xây dựng kịch bản FAQ cho chatbot CSKH. Hiện đã có 30/50 câu hỏi.',
    link: null, note: null, role: null, sourceSheet: 'Mai', sourceRow: 3,
    itTaskId: null, lastModified: '2026-05-19T08:30:00Z',
  },
  {
    id: 'MA3', project: 'App/Web AK phase 1.2', task: 'Màn hình lịch sử đơn hàng',
    owner: 'Mai', status: 'Golive', startDate: '2026-04-01', endDate: '2026-05-05',
    detail: 'Redesign màn hình lịch sử đơn hàng với filter theo trạng thái.',
    link: 'https://figma.com', note: null, role: null, sourceSheet: 'Mai', sourceRow: 4,
    itTaskId: 'TASK2605006', lastModified: '2026-05-05T14:00:00Z',
  },
];

export const MOCK_IT_TASKS: ITTaskRow[] = [
  {
    taskId: 'TASK2605001', month: '05/2026', stt: 1,
    task: 'Cổng thanh toán VNPay', priority: 'High',
    prdLink: 'https://docs.google.com', designLink: 'https://figma.com',
    status: 'Go live', itReview: true, timeline: '2026-05-18',
    pmNote: 'Đã test xong sandbox', itNote: 'Deploy production thành công',
  },
  {
    taskId: 'TASK2605002', month: '05/2026', stt: 2,
    task: 'Mô tả tính năng shop in shop', priority: 'Medium',
    prdLink: 'https://docs.google.com', designLink: null,
    status: 'Đang dev', itReview: false, timeline: '2026-05-31',
    pmNote: null, itNote: 'Đang implement backend API',
  },
  {
    taskId: 'TASK2605003', month: '05/2026', stt: 3,
    task: 'Màn hình giỏ hàng mobile', priority: 'High',
    prdLink: null, designLink: 'https://figma.com',
    status: 'Nghiệm thu', itReview: true, timeline: '2026-05-20',
    pmNote: 'Cần fix bug giỏ hàng empty state', itNote: null,
  },
  {
    taskId: 'TASK2605004', month: '05/2026', stt: 4,
    task: 'Triển khai chiến dịch cross-sell', priority: 'Medium',
    prdLink: 'https://docs.google.com', designLink: null,
    status: 'Đang dev', itReview: false, timeline: '2026-05-26',
    pmNote: null, itNote: 'Đang dev API bundle',
  },
  {
    taskId: 'TASK2605005', month: '05/2026', stt: 5,
    task: 'Luồng ticket support', priority: 'Low',
    prdLink: null, designLink: 'https://figma.com',
    status: 'Đang dev', itReview: false, timeline: '2026-05-22',
    pmNote: null, itNote: null,
  },
  {
    taskId: 'TASK2605006', month: '05/2026', stt: 6,
    task: 'Màn hình lịch sử đơn hàng', priority: 'Medium',
    prdLink: null, designLink: 'https://figma.com',
    status: 'Go live', itReview: true, timeline: '2026-05-05',
    pmNote: 'Đã golive', itNote: 'Deploy thành công 05/05',
  },
  {
    taskId: 'TASK2606001', month: '06/2026', stt: 1,
    task: 'Thay đổi thông tin người nhận hàng', priority: 'High',
    prdLink: 'https://docs.google.com', designLink: 'https://figma.com',
    status: 'Chuẩn bị làm', itReview: false, timeline: '2026-06-15',
    pmNote: null, itNote: null,
  },
  {
    taskId: 'TASK2604001', month: '04/2026', stt: 1,
    task: 'Màn hình trang chủ v2', priority: 'High',
    prdLink: null, designLink: 'https://figma.com',
    status: 'Go live', itReview: true, timeline: '2026-04-30',
    pmNote: 'Đã golive tháng 4', itNote: 'Done',
  },
];

export const MOCK_DASHBOARD: DashboardData = {
  totalActive: 11,
  goLiveThisMonth: 3,
  inProgress: 4,
  overdue: 2,
  byMember: [
    { member: 'Đức Anh', counts: { 'Add Xtask': 1, 'Add Sprint': 1, 'In progress': 1 } },
    { member: 'Khánh',   counts: { 'Add Sprint': 1, 'Nghiệm thu': 1, 'Chuẩn bị làm': 1 } },
    { member: 'Tuyền',   counts: { 'Add Sprint': 1, 'In progress': 1 } },
    { member: 'Trang',   counts: { 'Add Xtask': 1, 'Golive': 1 } },
    { member: 'Trình',   counts: { 'Định kỳ': 1, 'Chuẩn bị làm': 1 } },
    { member: 'Mai',     counts: { 'Add Sprint': 1, 'In progress': 1, 'Golive': 1 } },
  ],
  byMonth: [
    { month: 'T1', golive: 2, inprogress: 4, planned: 6 },
    { month: 'T2', golive: 3, inprogress: 5, planned: 5 },
    { month: 'T3', golive: 4, inprogress: 6, planned: 4 },
    { month: 'T4', golive: 5, inprogress: 4, planned: 3 },
    { month: 'T5', golive: 3, inprogress: 5, planned: 6 },
    { month: 'T6', golive: 0, inprogress: 3, planned: 8 },
    { month: 'T7', golive: 0, inprogress: 0, planned: 6 },
    { month: 'T8', golive: 0, inprogress: 0, planned: 5 },
    { month: 'T9', golive: 0, inprogress: 0, planned: 4 },
    { month: 'T10', golive: 0, inprogress: 0, planned: 3 },
    { month: 'T11', golive: 0, inprogress: 0, planned: 4 },
    { month: 'T12', golive: 0, inprogress: 0, planned: 2 },
  ],
  byProject: [
    { project: 'App/Web AK phase 1.2', count: 7 },
    { project: 'Tổng đơn bán kèm', count: 3 },
    { project: 'Chăm sóc khách hàng', count: 2 },
    { project: 'Shop in shop', count: 1 },
    { project: 'Phân tích dữ liệu', count: 1 },
    { project: 'Voucher & Khuyến mãi', count: 1 },
    { project: 'SEO & Performance', count: 1 },
  ],
  roadmap: [
    { quarter: 'Q1', done: 5, total: 5 },
    { quarter: 'Q2', done: 4, total: 6 },
    { quarter: 'Q3', done: 0, total: 6 },
    { quarter: 'Q4', done: 0, total: 4 },
  ],
};
