import type { TaskRow, ITTaskRow, DashboardData, DailyReport } from './types';

export const MOCK_TASKS: TaskRow[] = [
  {
    id: 'DA1', project: 'App/Web AK phase 1.2', task: 'Thay đổi thông tin người nhận hàng',
    owner: 'Đức Anh', status: 'Add Xtask', startDate: '2025-11-14', endDate: '2026-06-15',
    detail: '26/11: Trao đổi nhanh với IT về luồng thay đổi thông tin. Cần update màn hình checkout.',
    link: 'https://figma.com', note: null, role: 'PO', sourceSheet: 'Đức Anh', sourceRow: 2,
    itTaskId: 'TASK2606001', lastModified: '2026-05-18T10:00:00Z',
  },
  {
    id: 'DA2', project: 'App/Web AK phase 1.2', task: 'Cổng thanh toán VNPay',
    owner: 'Đức Anh', status: 'Add Sprint', startDate: '2026-04-01', endDate: '2026-05-18',
    detail: 'Tích hợp VNPay vào luồng thanh toán. Đã hoàn thành test sandbox.',
    link: null, note: 'Cần review lại với team IT', role: 'PO', sourceSheet: 'Đức Anh', sourceRow: 3,
    itTaskId: 'TASK2605001', lastModified: '2026-05-17T09:00:00Z',
  },
  {
    id: 'DA3', project: 'Tổng đơn bán kèm', task: 'Thiết kế luồng bundle sản phẩm',
    owner: 'Đức Anh', status: 'In progress', startDate: '2026-05-01', endDate: '2026-05-30',
    detail: 'Thiết kế luồng cho tính năng bundle sản phẩm kèm theo khi checkout.',
    link: 'https://figma.com', note: null, role: 'PO', sourceSheet: 'Đức Anh', sourceRow: 4,
    itTaskId: null, lastModified: '2026-05-19T08:00:00Z',
  },
  {
    id: 'KH1', project: 'Shop in shop', task: 'Mô tả tính năng shop in shop',
    owner: 'Khánh', status: 'Add Sprint', startDate: '2026-05-10', endDate: '2026-05-31',
    detail: 'Mô tả đầy đủ tính năng shop in shop cho các đối tác thương hiệu lớn.',
    link: null, note: null, role: 'PD', sourceSheet: 'Khánh', sourceRow: 2,
    itTaskId: 'TASK2605002', lastModified: '2026-05-18T14:00:00Z',
  },
  {
    id: 'KH2', project: 'App/Web AK phase 1.2', task: 'Màn hình giỏ hàng mobile',
    owner: 'Khánh', status: 'Nghiệm thu', startDate: '2026-04-15', endDate: '2026-05-20',
    detail: 'Redesign màn hình giỏ hàng cho mobile, cải thiện UX checkout.',
    link: 'https://figma.com', note: null, role: 'PD', sourceSheet: 'Khánh', sourceRow: 3,
    itTaskId: 'TASK2605003', lastModified: '2026-05-19T09:00:00Z',
  },
  {
    id: 'KH3', project: 'Roadmap Q3', task: 'PRD tính năng loyalty points',
    owner: 'Khánh', status: 'Chuẩn bị làm', startDate: null, endDate: '2026-07-01',
    detail: null, link: null, note: null, role: 'PD', sourceSheet: 'Khánh', sourceRow: 4,
    itTaskId: null, lastModified: '2026-05-15T10:00:00Z',
  },
  {
    id: 'TY1', project: 'Tổng đơn bán kèm', task: 'Triển khai chiến dịch cross-sell',
    owner: 'Tuyền', status: 'Add Sprint', startDate: '2026-05-05', endDate: '2026-05-26',
    detail: 'Triển khai chiến dịch bán kèm cho mùa hè 2026.',
    link: null, note: null, role: 'DA', sourceSheet: 'Tuyền', sourceRow: 2,
    itTaskId: 'TASK2605004', lastModified: '2026-05-18T11:00:00Z',
  },
  {
    id: 'TY2', project: 'Tổng đơn bán kèm', task: 'Định hình danh sách sản phẩm kèm',
    owner: 'Tuyền', status: 'Done', startDate: '2026-04-01', endDate: '2026-04-10',
    detail: 'Đã hoàn thành danh sách 50 sản phẩm kèm ưu tiên.',
    link: null, note: null, role: 'DA', sourceSheet: 'Tuyền', sourceRow: 3,
    itTaskId: null, lastModified: '2026-04-10T15:00:00Z',
  },
  {
    id: 'TY3', project: 'Voucher & Khuyến mãi', task: 'Luồng áp dụng voucher',
    owner: 'Tuyền', status: 'In progress', startDate: '2026-05-12', endDate: '2026-06-01',
    detail: 'Mô tả luồng áp dụng voucher khi checkout, bao gồm stack discount.',
    link: 'https://docs.google.com', note: null, role: 'DA', sourceSheet: 'Tuyền', sourceRow: 4,
    itTaskId: null, lastModified: '2026-05-19T07:00:00Z',
  },
  {
    id: 'TR1', project: 'App/Web AK phase 1.2', task: 'Màn hình trang chủ v2',
    owner: 'Trang', status: 'Golive', startDate: '2026-03-01', endDate: '2026-04-30',
    detail: 'Redesign hoàn toàn trang chủ với banner động và section sản phẩm mới.',
    link: 'https://figma.com', note: null, role: 'PMC', sourceSheet: 'Trang', sourceRow: 2,
    itTaskId: 'TASK2604001', lastModified: '2026-04-30T16:00:00Z',
  },
  {
    id: 'TR2', project: 'SEO & Performance', task: 'Tối ưu Core Web Vitals',
    owner: 'Trang', status: 'Add Xtask', startDate: '2026-05-01', endDate: '2026-05-25',
    detail: 'Cải thiện LCP, FID, CLS theo checklist từ team IT.',
    link: null, note: 'Chờ team IT deploy xong phase 1.2', role: 'PMC', sourceSheet: 'Trang', sourceRow: 3,
    itTaskId: null, lastModified: '2026-05-17T12:00:00Z',
  },
  {
    id: 'TI1', project: 'Phân tích dữ liệu', task: 'Dashboard báo cáo tuần',
    owner: 'Trình', status: 'Định kỳ', startDate: '2026-01-01', endDate: null,
    detail: 'Báo cáo số liệu tuần cho BGĐ: doanh thu, đơn hàng, conversion rate.',
    link: 'https://lookerstudio.google.com', note: null, role: null, sourceSheet: 'Trình', sourceRow: 2,
    itTaskId: null, lastModified: '2026-05-18T17:00:00Z',
  },
  {
    id: 'TI2', project: 'App/Web AK phase 1.3', task: 'Nghiên cứu tính năng AR try-on',
    owner: 'Trình', status: 'Chuẩn bị làm', startDate: null, endDate: '2026-08-01',
    detail: null, link: null, note: null, role: null, sourceSheet: 'Trình', sourceRow: 3,
    itTaskId: null, lastModified: '2026-05-10T09:00:00Z',
  },
  {
    id: 'MA1', project: 'Chăm sóc khách hàng', task: 'Luồng ticket support',
    owner: 'Mai', status: 'Add Sprint', startDate: '2026-05-08', endDate: '2026-05-22',
    detail: 'Thiết kế luồng ticket support tích hợp vào app AK.',
    link: 'https://figma.com', note: null, role: null, sourceSheet: 'Mai', sourceRow: 2,
    itTaskId: 'TASK2605005', lastModified: '2026-05-18T10:30:00Z',
  },
  {
    id: 'MA2', project: 'Chăm sóc khách hàng', task: 'FAQ tự động chatbot',
    owner: 'Mai', status: 'In progress', startDate: '2026-05-15', endDate: '2026-06-10',
    detail: 'Xây dựng kịch bản FAQ cho chatbot CSKH. Hiện đã có 30/50 câu hỏi.',
    link: null, note: null, role: null, sourceSheet: 'Mai', sourceRow: 3,
    itTaskId: null, lastModified: '2026-05-19T08:30:00Z',
  },
  {
    id: 'MA3', project: 'App/Web AK phase 1.2', task: 'Màn hình lịch sử đơn hàng',
    owner: 'Mai', status: 'Golive', startDate: '2026-04-01', endDate: '2026-05-05',
    detail: 'Redesign màn hình lịch sử đơn hàng với filter theo trạng thái.',
    link: 'https://figma.com', note: null, role: null, sourceSheet: 'Mai', sourceRow: 4,
    itTaskId: 'TASK2605006', lastModified: '2026-05-05T14:00:00Z',
  },
];

export const MOCK_IT_TASKS: ITTaskRow[] = [
  // ── Tháng 04/2026 ──────────────────────────────────────────────────────────
  {
    taskId: 'TASK2604001', month: '04/2026', stt: 1,
    task: 'Landing page mới', priority: 'High',
    prdLink: null, designLink: 'https://www.figma.com/file/abc',
    status: 'Go live', itReview: true, timeline: '2026-04-14',
    pmNote: null, itNote: null,
  },
  {
    taskId: 'TASK2604006', month: '04/2026', stt: 2,
    task: 'Thêm khung giờ flash sale', priority: 'Medium',
    prdLink: 'https://docs.google.com/document/d/abc', designLink: 'https://www.figma.com/file/def',
    status: 'Go live', itReview: true, timeline: '2026-05-07',
    pmNote: null, itNote: null,
  },
  {
    taskId: 'TASK2604007', month: '04/2026', stt: 3,
    task: 'Update rule search đích danh sản phẩm tool tra giá', priority: 'Medium',
    prdLink: 'https://docs.google.com/document/d/def', designLink: 'https://www.figma.com/file/ghi',
    status: 'Go live', itReview: true, timeline: '2026-05-07',
    pmNote: 'Check và chuyển search đích danh bằng tên món', itNote: null,
  },
  {
    taskId: 'TASK2604008', month: '04/2026', stt: 4,
    task: 'Thêm filter hàng trang NH Cha (NH cấp 1)', priority: 'Medium',
    prdLink: null, designLink: 'https://www.figma.com/file/jkl',
    status: 'Go live', itReview: true, timeline: '2026-05-15',
    pmNote: 'Đã gửi cuối tháng 3', itNote: null,
  },
  {
    taskId: 'TASK2604005', month: '04/2026', stt: 5,
    task: 'Bổ sung trạng thái đối với đơn hàng nhập trả', priority: 'Low',
    prdLink: null, designLink: null,
    status: 'Đang dev', itReview: true, timeline: '2026-05-08',
    pmNote: null, itNote: null,
  },
  {
    taskId: 'TASK2604004', month: '04/2026', stt: 6,
    task: 'Hết quả hoàn tiền', priority: 'Medium',
    prdLink: 'https://docs.google.com/document/d/ghi', designLink: 'https://www.figma.com/file/mno',
    status: 'Đang dev', itReview: true, timeline: '2026-05-11',
    pmNote: null, itNote: 'Tâm ngồi với Gấm',
  },
  {
    taskId: 'TASK2604003', month: '04/2026', stt: 7,
    task: 'Cổng thanh toán VNPay', priority: 'High',
    prdLink: null, designLink: null,
    status: 'Đang dev', itReview: true, timeline: '2026-05-18',
    pmNote: 'Không cần mô tả', itNote: null,
  },
  {
    taskId: 'TASK2604009', month: '04/2026', stt: 8,
    task: 'Shortcode ô sản phẩm bài tin', priority: 'High',
    prdLink: null, designLink: null,
    status: 'Đang dev', itReview: true, timeline: '2026-05-19',
    pmNote: 'Không cần mô tả', itNote: null,
  },
  {
    taskId: 'TASK2604002', month: '04/2026', stt: 9,
    task: 'Mua kèm tổng đơn', priority: 'High',
    prdLink: 'https://docs.google.com/document/d/jkl', designLink: 'https://www.figma.com/file/pqr',
    status: 'Đang dev', itReview: true, timeline: '2026-05-22',
    pmNote: null, itNote: null,
  },
  // ── Tháng 05/2026 ──────────────────────────────────────────────────────────
  {
    taskId: 'TASK2605001', month: '05/2026', stt: 1,
    task: 'Màn hình giỏ hàng mobile v2', priority: 'High',
    prdLink: null, designLink: 'https://www.figma.com/file/stu',
    status: 'Go live', itReview: true, timeline: '2026-05-20',
    pmNote: null, itNote: 'Deploy production thành công',
  },
  {
    taskId: 'TASK2605002', month: '05/2026', stt: 2,
    task: 'Màn hình lịch sử đơn hàng', priority: 'Medium',
    prdLink: null, designLink: 'https://www.figma.com/file/vwx',
    status: 'Go live', itReview: true, timeline: '2026-05-05',
    pmNote: 'Đã golive', itNote: 'Deploy thành công 05/05',
  },
  {
    taskId: 'TASK2605003', month: '05/2026', stt: 3,
    task: 'Tích hợp VNPay sandbox', priority: 'High',
    prdLink: 'https://docs.google.com/document/d/mno', designLink: 'https://www.figma.com/file/yza',
    status: 'Nghiệm thu', itReview: true, timeline: '2026-05-25',
    pmNote: 'Cần test lại flow hoàn tiền', itNote: null,
  },
  {
    taskId: 'TASK2605004', month: '05/2026', stt: 4,
    task: 'Mô tả tính năng shop in shop', priority: 'Medium',
    prdLink: 'https://docs.google.com/document/d/pqr', designLink: null,
    status: 'Đang dev', itReview: false, timeline: '2026-05-31',
    pmNote: null, itNote: 'Đang implement backend API',
  },
  {
    taskId: 'TASK2605005', month: '05/2026', stt: 5,
    task: 'Triển khai chiến dịch cross-sell', priority: 'Medium',
    prdLink: 'https://docs.google.com/document/d/stu', designLink: null,
    status: 'Đang dev', itReview: false, timeline: '2026-05-26',
    pmNote: null, itNote: 'Đang dev API bundle',
  },
  {
    taskId: 'TASK2605006', month: '05/2026', stt: 6,
    task: 'Luồng ticket support CSKH', priority: 'Low',
    prdLink: null, designLink: 'https://www.figma.com/file/bcd',
    status: 'Đang dev', itReview: false, timeline: '2026-05-22',
    pmNote: null, itNote: null,
  },
  // ── Tháng 06/2026 ──────────────────────────────────────────────────────────
  {
    taskId: 'TASK2606001', month: '06/2026', stt: 1,
    task: 'Thay đổi thông tin người nhận hàng', priority: 'High',
    prdLink: 'https://docs.google.com/document/d/vwx', designLink: 'https://www.figma.com/file/efg',
    status: 'Chuẩn bị làm', itReview: false, timeline: '2026-06-15',
    pmNote: null, itNote: null,
  },
  {
    taskId: 'TASK2606002', month: '06/2026', stt: 2,
    task: 'Tính năng loyalty points', priority: 'High',
    prdLink: 'https://docs.google.com/document/d/yza', designLink: null,
    status: 'Chuẩn bị làm', itReview: false, timeline: '2026-06-30',
    pmNote: 'PRD đang hoàn thiện', itNote: null,
  },
  {
    taskId: 'TASK2606003', month: '06/2026', stt: 3,
    task: 'Trang chi tiết sản phẩm — tab đánh giá', priority: 'Medium',
    prdLink: null, designLink: 'https://www.figma.com/file/hij',
    status: 'Chuẩn bị làm', itReview: false, timeline: '2026-06-20',
    pmNote: null, itNote: null,
  },
];

// ─── Pool Tasks (chưa được assign, để thành viên pick) ───────────────────────
export const MOCK_POOL_TASKS: TaskRow[] = [
  {
    id: 'POOL1', project: 'App/Web AK phase 1.2', task: 'Màn hình đăng nhập / đăng ký v2',
    owner: '', status: 'Chuẩn bị đưa vào làm', startDate: null, endDate: '2026-06-30',
    detail: 'Redesign lại màn hình auth, bổ sung login bằng Zalo, Google. UX tối ưu hơn.',
    link: 'https://figma.com', note: null, role: 'PD',
    sourceSheet: 'Pool', sourceRow: 2, itTaskId: null, lastModified: '2026-05-18T08:00:00Z',
  },
  {
    id: 'POOL2', project: 'App/Web AK phase 1.2', task: 'Trang chi tiết sản phẩm — tab đánh giá',
    owner: '', status: 'Backlog', startDate: null, endDate: '2026-07-15',
    detail: 'Thêm tab đánh giá sản phẩm: rating, filter theo sao, ảnh từ khách.',
    link: null, note: 'Đã có wireframe từ tháng 4', role: 'PD',
    sourceSheet: 'Pool', sourceRow: 3, itTaskId: null, lastModified: '2026-05-10T09:00:00Z',
  },
  {
    id: 'POOL3', project: 'Voucher & Khuyến mãi', task: 'Luồng voucher sinh nhật tự động',
    owner: '', status: 'Chuẩn bị đưa vào làm', startDate: null, endDate: '2026-06-20',
    detail: 'Hệ thống tự tạo voucher sinh nhật cho thành viên, gửi push notification.',
    link: 'https://docs.google.com', note: null, role: 'DA',
    sourceSheet: 'Pool', sourceRow: 4, itTaskId: null, lastModified: '2026-05-15T10:00:00Z',
  },
  {
    id: 'POOL4', project: 'Shop in shop', task: 'Thiết kế trang partner dashboard',
    owner: '', status: 'Backlog', startDate: null, endDate: '2026-08-01',
    detail: 'Dashboard cho đối tác thương hiệu xem doanh số, đơn hàng shop in shop.',
    link: 'https://figma.com', note: null, role: 'PD',
    sourceSheet: 'Pool', sourceRow: 5, itTaskId: null, lastModified: '2026-05-12T11:00:00Z',
  },
  {
    id: 'POOL5', project: 'Phân tích dữ liệu', task: 'Báo cáo funnel chuyển đổi tháng',
    owner: '', status: 'Định kỳ', startDate: '2026-06-01', endDate: '2026-06-05',
    detail: 'Phân tích funnel từ view → cart → checkout → payment mỗi tháng.',
    link: null, note: null, role: 'DA',
    sourceSheet: 'Pool', sourceRow: 6, itTaskId: null, lastModified: '2026-05-16T08:30:00Z',
  },
  {
    id: 'POOL6', project: 'Chăm sóc khách hàng', task: 'SOP xử lý khiếu nại đổi trả',
    owner: '', status: 'Chuẩn bị đưa vào làm', startDate: null, endDate: '2026-06-15',
    detail: 'Xây dựng quy trình xử lý khiếu nại đổi trả chuẩn cho team CSKH.',
    link: 'https://docs.google.com', note: 'Phối hợp với team Ops', role: 'PMC',
    sourceSheet: 'Pool', sourceRow: 7, itTaskId: null, lastModified: '2026-05-17T14:00:00Z',
  },
  {
    id: 'POOL7', project: 'Roadmap Q3', task: 'Nghiên cứu tính năng subscription',
    owner: '', status: 'Backlog', startDate: null, endDate: '2026-09-01',
    detail: 'Khảo sát và nghiên cứu mô hình subscription cho sản phẩm tiêu dùng thường xuyên.',
    link: null, note: null, role: 'PO',
    sourceSheet: 'Pool', sourceRow: 8, itTaskId: null, lastModified: '2026-05-14T10:00:00Z',
  },
  {
    id: 'POOL8', project: 'App/Web AK phase 1.3', task: 'PRD tính năng live stream bán hàng',
    owner: '', status: 'Chuẩn bị đưa vào làm', startDate: null, endDate: '2026-07-30',
    detail: 'Viết PRD cho tính năng live stream: host, viewer, giỏ hàng trong stream.',
    link: 'https://docs.google.com', note: null, role: 'PO',
    sourceSheet: 'Pool', sourceRow: 9, itTaskId: null, lastModified: '2026-05-19T09:00:00Z',
  },
  {
    id: 'POOL9', project: 'SEO & Performance', task: 'Audit URL structure và canonical',
    owner: '', status: 'Backlog', startDate: null, endDate: '2026-06-30',
    detail: 'Kiểm tra toàn bộ URL structure, bổ sung canonical tag, xử lý duplicate content.',
    link: null, note: null, role: 'PMC',
    sourceSheet: 'Pool', sourceRow: 10, itTaskId: null, lastModified: '2026-05-13T11:00:00Z',
  },
  {
    id: 'POOL10', project: 'Tổng đơn bán kèm', task: 'A/B test vị trí hiển thị bundle',
    owner: '', status: 'Chuẩn bị đưa vào làm', startDate: '2026-06-01', endDate: '2026-06-20',
    detail: 'Thực hiện A/B test: hiển thị bundle trước hay sau khi add cart.',
    link: null, note: 'Cần phối hợp IT để setup experiment', role: 'DA',
    sourceSheet: 'Pool', sourceRow: 11, itTaskId: null, lastModified: '2026-05-18T15:00:00Z',
  },
];

// ─── Mock Daily Reports ───────────────────────────────────────────────────────
export const MOCK_REPORTS: DailyReport[] = [
  {
    id: 'RPT001', date: '2026-05-21', reportPeriod: 'day' as const, member: 'Đức Anh', role: 'PO',
    project: 'App/Web AK phase 1.2', progress: 75, reportStatus: 'on-track',
    todayWork: 'Hoàn thành thiết kế màn hình checkout v2, review mockup với team IT, cập nhật PRD phần thanh toán VNPay.',
    tomorrowPlan: 'Demo màn hình checkout với PM, bắt đầu thiết kế màn hình xác nhận đơn hàng.',
    blockers: 'API VNPay sandbox đang bị lỗi, chờ team IT fix.',
    submittedAt: '2026-05-21T17:30:00Z',
  },
  {
    id: 'RPT002', date: '2026-05-21', reportPeriod: 'day' as const, member: 'Khánh', role: 'DA',
    project: 'Shop in shop', progress: 40, reportStatus: 'delayed',
    todayWork: 'Viết mô tả tính năng quản lý gian hàng partner, tham gia meeting với BD team về yêu cầu.',
    tomorrowPlan: 'Hoàn thiện user story cho flow đăng ký partner, chuẩn bị slide báo cáo sprint.',
    blockers: 'Chờ xác nhận yêu cầu từ BD về hoa hồng — đã gửi email 3 ngày chưa nhận phản hồi.',
    submittedAt: '2026-05-21T17:15:00Z',
  },
  {
    id: 'RPT003', date: '2026-05-21', reportPeriod: 'day' as const, member: 'Tuyền', role: null,
    project: 'Tổng đơn bán kèm', progress: 90, reportStatus: 'on-track',
    todayWork: 'Hoàn thiện danh sách sản phẩm kèm ưu tiên cho chiến dịch cross-sell tháng 6, gửi team IT triển khai.',
    tomorrowPlan: 'Theo dõi kết quả A/B test tuần 1, chuẩn bị báo cáo hiệu quả cross-sell tháng 5.',
    blockers: null,
    submittedAt: '2026-05-21T17:45:00Z',
  },
  {
    id: 'RPT004', date: '2026-05-21', reportPeriod: 'day' as const, member: 'Trang', role: 'PMC',
    project: 'SEO & Performance', progress: 55, reportStatus: 'need-support',
    todayWork: 'Audit Core Web Vitals trang chủ và trang category, xác định 12 điểm cần tối ưu.',
    tomorrowPlan: 'Trao đổi với team IT về các điểm cần fix phía server, lên kế hoạch sprint tối ưu.',
    blockers: 'Cần quyền truy cập Google Search Console — đã request IT tuần trước nhưng chưa được cấp. Cần support từ PM.',
    submittedAt: '2026-05-21T18:00:00Z',
  },
  {
    id: 'RPT005', date: '2026-05-20', reportPeriod: 'day' as const, member: 'Đức Anh', role: 'PO',
    project: 'App/Web AK phase 1.2', progress: 65, reportStatus: 'on-track',
    todayWork: 'Thiết kế màn hình giỏ hàng mobile v2, trao đổi với Khánh về flow UX.',
    tomorrowPlan: 'Tiếp tục màn hình checkout, chuẩn bị nội dung review sprint.',
    blockers: null,
    submittedAt: '2026-05-20T17:30:00Z',
  },
  {
    id: 'RPT006', date: '2026-05-20', reportPeriod: 'day' as const, member: 'Mai', role: null,
    project: 'Chăm sóc khách hàng', progress: 60, reportStatus: 'on-track',
    todayWork: 'Hoàn thành 35/50 kịch bản FAQ chatbot, review nội dung với team CSKH.',
    tomorrowPlan: 'Hoàn thiện 15 câu FAQ còn lại, bắt đầu thiết kế luồng escalation.',
    blockers: null,
    submittedAt: '2026-05-20T17:00:00Z',
  },
  {
    id: 'RPT007', date: '2026-05-20', reportPeriod: 'day' as const, member: 'Trình', role: null,
    project: 'Phân tích dữ liệu', progress: 80, reportStatus: 'on-track',
    todayWork: 'Hoàn thiện dashboard báo cáo tuần với 5 chart mới, cập nhật công thức tính conversion rate.',
    tomorrowPlan: 'Gửi dashboard cho BGĐ review, bắt đầu phân tích funnel tháng 5.',
    blockers: null,
    submittedAt: '2026-05-20T16:30:00Z',
  },
  {
    id: 'RPT008', date: '2026-05-19', reportPeriod: 'day' as const, member: 'Khánh', role: 'DA',
    project: 'App/Web AK phase 1.2', progress: 95, reportStatus: 'on-track',
    todayWork: 'Nghiệm thu màn hình giỏ hàng mobile với team IT, tạo bug list 3 issue nhỏ cần fix.',
    tomorrowPlan: 'Theo dõi fix bug giỏ hàng, bắt đầu PRD loyalty points.',
    blockers: null,
    submittedAt: '2026-05-19T17:30:00Z',
  },
];

export const MOCK_DASHBOARD: DashboardData = {
  totalActive: 11,
  goLiveThisMonth: 3,
  inProgress: 4,
  overdue: 2,
  byMember: [
    { member: 'Đức Anh', counts: { 'Add Xtask': 1, 'Add Sprint': 1, 'In progress': 1 } },
    { member: 'Khánh',   counts: { 'Add Sprint': 1, 'Nghiệm thu': 1, 'Chuẩn bị làm': 1 } },
    { member: 'Tuyền',   counts: { 'Add Sprint': 1, 'In progress': 1 } },
    { member: 'Trang',   counts: { 'Add Xtask': 1, 'Golive': 1 } },
    { member: 'Trình',   counts: { 'Định kỳ': 1, 'Chuẩn bị làm': 1 } },
    { member: 'Mai',     counts: { 'Add Sprint': 1, 'In progress': 1, 'Golive': 1 } },
  ],
  byMonth: [
    { month: 'T1', golive: 2, inprogress: 4, planned: 6 },
    { month: 'T2', golive: 3, inprogress: 5, planned: 5 },
    { month: 'T3', golive: 4, inprogress: 6, planned: 4 },
    { month: 'T4', golive: 5, inprogress: 4, planned: 3 },
    { month: 'T5', golive: 3, inprogress: 5, planned: 6 },
    { month: 'T6', golive: 0, inprogress: 3, planned: 8 },
    { month: 'T7', golive: 0, inprogress: 0, planned: 6 },
    { month: 'T8', golive: 0, inprogress: 0, planned: 5 },
    { month: 'T9', golive: 0, inprogress: 0, planned: 4 },
    { month: 'T10', golive: 0, inprogress: 0, planned: 3 },
    { month: 'T11', golive: 0, inprogress: 0, planned: 4 },
    { month: 'T12', golive: 0, inprogress: 0, planned: 2 },
  ],
  byProject: [
    { project: 'App/Web AK phase 1.2', count: 7 },
    { project: 'Tổng đơn bán kèm', count: 3 },
    { project: 'Chăm sóc khách hàng', count: 2 },
    { project: 'Shop in shop', count: 1 },
    { project: 'Phân tích dữ liệu', count: 1 },
    { project: 'Voucher & Khuyến mãi', count: 1 },
    { project: 'SEO & Performance', count: 1 },
  ],
  roadmap: [
    { quarter: 'Q1', done: 5, total: 5 },
    { quarter: 'Q2', done: 4, total: 6 },
    { quarter: 'Q3', done: 0, total: 6 },
    { quarter: 'Q4', done: 0, total: 4 },
  ],
};
